"use client";

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-20">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold mb-6">Disclaimer</h1>
        <p className="text-sm text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString()}
        </p>

        <div className="prose prose-lg max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-bold mb-4">General Information</h2>
            <p className="text-muted-foreground">
              The information provided by WhatTheFood is for general informational purposes only.
              While we strive to keep information accurate and up to date, we make no
              representations or warranties of any kind about the completeness, accuracy,
              reliability, or availability of the information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Not Medical Advice</h2>
            <p className="text-muted-foreground">
              WhatTheFood does not provide medical, health, or nutrition advice. Any information
              provided should not be used as a substitute for professional medical advice,
              diagnosis, or treatment. Always seek the advice of a qualified health provider with
              any questions you may have regarding a medical condition or dietary needs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">AI Output</h2>
            <p className="text-muted-foreground">
              Outputs generated by AI may be inaccurate, incomplete, or inappropriate. You are
              responsible for verifying information before relying on it, especially for
              decisions that may impact health or wellbeing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">External Links</h2>
            <p className="text-muted-foreground">
              Our website may contain links to external sites that are not provided or maintained
              by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of
              any information on external websites.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground">
              To the fullest extent permitted by law, WhatTheFood and its owners, affiliates, and
              partners will not be liable for any loss or damage arising from the use of our
              website, services, or AI outputs.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

